- name: copy logstash config
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: stop logstash
  systemd:
    name: logstash
    state: stopped

- name: Waits for port 5044 to be stopped
  wait_for:
    port: 5044
    delay: 15
    state: stopped

- name: Start Logstash
  systemd:
    name: logstash
    state: started

- name: Waits for port 5044 to be started
  wait_for:
    port: 5044
    delay: 15
    state: started