- name: Include Github download
  include_tasks: download-from-github.yml
  when: APP_VERSION == "null"

- name: Include Nexus download
  include_tasks: download-from-nexus.yml
  when: APP_VERSION != "null"