- name: add roboshop user
  user:
    name: roboshop
  register: ROBOSHOP_USER
  when: APP_TYPE == "backend"

- name: download archive
  get_url:
    url: http://172.31.15.180:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}-.zip
    dest: /tmp/{{COMPONENT}}-{{APP_VERSION}}-.zip
    username: bar
    password: '{{ mysecret }}'

- name: Remove old content
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent

- name: extract the {{COMPONENT}} archive
  ansible.builtin.unarchive:
    src: "/tmp/{{COMPONENT}}-{{APP_VERSION}}-.zip"
    dest: {{APP_PATH}}/
    remote_src: yes



#- name: copy the extracted content to {{COMPONENT}} path
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: /home/roboshop/{{COMPONENT}}/
#    remote_src: yes
#    owner: roboshop
#    group: roboshop
#  when: APP_TYPE == "backend"
#
#- name: Copy extracted content to nginx path
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/static/
#    dest: "{{APP_PATH}}/"
#    remote_src: yes
#  when: APP_TYPE == "fronten"