global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#random'
        send_resolved: true
        text: {%raw%}"<!channel> \nsummary: {{ .CommonAnnotations.summary }}"{%endraw%}

#receivers:
#  - name: email
#    email_configs:
#      - to: manjushagudiwada@gmail.com
#        from: manjushagudiwada@gmail.com
#        smarthost: email-smtp.AWS_SES_REGION.amazonaws.com:587
#        auth_username: AWS_SES_SMTP_USERNAME
#        auth_password: AWS_SES_SMTP_PASSWORD
#        require_tls: yes
#        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
